const types = {
  LOGIN_INFO: 'LOGIN_INFO',
  IS_FETCHING: 'IS_FETCHING',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  MEAL_RECIPES_RESULTS: 'MEAL_RECIPES_RESULTS',
  DRINK_RECIPES_RESULTS: 'DRINK_RECIPES_RESULTS',
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  REMOVE_FAVOURITES: 'REMOVE_FAVOURITES',
  START_RECIPE: 'START_RECIPE',
  START_RECIPE_DRINK: 'START_RECIPE_DRINK',
};

export default types;
